### ISSUE TITLE
مشکل در نسخه ریلیز

### ISSUE THREAD

**Issue by saeedek** [tapsellorg/TapsellSDK-ReactNativePlugin#4]
با سلام و ممنون از کتابخونه
من یه مشکلی دارم ، برناممو که به صورت دیباگ اجرا می کنم مشکلی نداره تبلیغات رو می تونم ببینم ولی توی نسخه ریلیز تبلیغات نشون داده نمی شن ، و ارروری که دریافت می کنم اینه که گوشی به اینترنت متصل نیست.
با نسخه 28 اندروید کامپایل کردم و نسخه ریکت نیتیو هم 
0.61.5
هست.
ممنون میشم کمک کنید
با تشکر

**Comment by saeedek** [comment]
`2020-03-31 14:13:05.291 7631-7631/com.toolbox W/System.err: java.lang.NullPointerException: throw with null exception
2020-03-31 14:13:05.291 7631-7631/com.toolbox W/System.err:     at ir.tapsell.sdk.j.c.a.a.b(Unknown Source:3)
2020-03-31 14:13:05.291 7631-7631/com.toolbox W/System.err:     at ir.tapsell.sdk.i.c.g(Unknown Source:67)
2020-03-31 14:13:05.291 7631-7631/com.toolbox W/System.err:     at ir.tapsell.sdk.aa.a(Unknown Source:82)
2020-03-31 14:13:05.291 7631-7631/com.toolbox W/System.err:     at ir.tapsell.sdk.Z.a(Unknown Source:48)
2020-03-31 14:13:05.291 7631-7631/com.toolbox W/System.err:     at ir.tapsell.sdk.Z.b(Unknown Source:2)
2020-03-31 14:13:05.291 7631-7631/com.toolbox W/System.err:     at ir.tapsell.sdk.e.b.a(Unknown Source:10)
2020-03-31 14:13:05.291 7631-7631/com.toolbox W/System.err:     at f.n.run(Unknown Source:37)
2020-03-31 14:13:05.291 7631-7631/com.toolbox W/System.err:     at android.os.Handler.handleCallback(Handler.java:883)
2020-03-31 14:13:05.291 7631-7631/com.toolbox W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:100)
2020-03-31 14:13:05.291 7631-7631/com.toolbox W/System.err:     at android.os.Looper.loop(Looper.java:237)
2020-03-31 14:13:05.291 7631-7631/com.toolbox W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7777)
2020-03-31 14:13:05.291 7631-7631/com.toolbox W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2020-03-31 14:13:05.291 7631-7631/com.toolbox W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
2020-03-31 14:13:05.291 7631-7631/com.toolbox W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1047)
`
این از لاگ کت موقعی که می خواد تبلیغ نشون بده

**Comment by moh3n9595** [comment]
Same issue

**Comment by saeedek** [comment]
> Same issue

باید 
progaurd.rule
رو از توی پروژه مثالشون کپی کنی برا پروژه خودت.

**Comment by moh3n9595** [comment]
Thanks @saeedek, I'm going to check your solution.
Unfortunately, we encounter with poor documentation.

**Comment by moh3n9595** [comment]
As @saeedek said when proguard is enabled, some error rises.
Can you add some more docs as a readme file?
A better solution can be the demarcation of PRs (Are they be welcomed @tapsellorg?).

**Comment by aliunco** [comment]
I've just received the same issue with the SDK in Android, here is my react-native info

```
System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz
    Memory: 109.26 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.13.0 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 25, 27, 28, 29
      Build Tools: 27.0.3, 28.0.3, 29.0.2
      System Images: android-28 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.2 AI-181.5540.7.32.5056338
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_121 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.3 => 0.63.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

@saeedek 
Would you please mention the sample project here? or maybe it would be better to print the progaurd.rule here.
🙏🏻

**Comment by aliunco** [comment]
I've found the proguard file and here it is: (just past these code inside the android->app->proguard-rules.pro)

```
-keepattributes Signature
-keepattributes *Annotation*
-keepattributes EnclosingMethod
-keepattributes InnerClasses

-keep class sun.misc.Unsafe { *; }
-dontwarn sun.misc.**
-keep class * implements com.google.gson.TypeAdapterFactory
-keep class * implements com.google.gson.JsonSerializer
-keep class * implements com.google.gson.JsonDeserializer

# Retrofit does reflection on generic parameters. InnerClasses is required to use Signature and
# EnclosingMethod is required to use InnerClasses.
-keepattributes Signature, InnerClasses, EnclosingMethod

# Retain service method parameters when optimizing.
-keepclassmembers,allowshrinking,allowobfuscation interface * {
    @retrofit2.http.* <methods>;
}

# Ignore annotation used for build tooling.
-dontwarn org.codehaus.mojo.animal_sniffer.IgnoreJRERequirement

# Ignore JSR 305 annotations for embedding nullability information.
-dontwarn javax.annotation.**

# Guarded by a NoClassDefFoundError try/catch and only used when on the classpath.
-dontwarn kotlin.Unit

# Top-level functions that can only be used by Kotlin.
-dontwarn retrofit2.-KotlinExtensions

# JSR 305 annotations are for embedding nullability information.
-dontwarn javax.annotation.**

# A resource is loaded with a relative path so the package of this class must be preserved.
-keepnames class okhttp3.internal.publicsuffix.PublicSuffixDatabase

# Animal Sniffer compileOnly dependency to ensure APIs are compatible with older versions of Java.
-dontwarn org.codehaus.mojo.animal_sniffer.*

# OkHttp platform used only on JVM and when Conscrypt dependency is available.
-dontwarn okhttp3.internal.platform.ConscryptPlatform

# Animal Sniffer compileOnly dependency to ensure APIs are compatible with older versions of Java.
-dontwarn org.codehaus.mojo.animal_sniffer.*


-keepclassmembers enum * { *; }
-keep class **.R$* { *; }
-keep interface ir.tapsell.sdk.NoProguard
-keep class * implements ir.tapsell.sdk.NoProguard { *; }
-keep interface * extends ir.tapsell.sdk.NoProguard { *; }
-keep enum * extends ir.tapsell.sdk.NoProguard { *; }
-keepnames class * extends android.app.Activity
-keep class ir.tapsell.sdk.models.** { *; }

-keep class com.google.obf.** { *; }
-keep interface com.google.obf.** { *; }

-keep class com.google.ads.interactivemedia.** { *; }
-keep interface com.google.ads.interactivemedia.** { *; }

# For Google Play Services
-keep public class com.google.android.gms.ads.**{
   public *;
}

# For old ads classes
-keep public class com.google.ads.**{
   public *;
}

# Other required classes for Google Play Services
# Read more at http://developer.android.com/google/play-services/setup.html
-keep class * extends java.util.ListResourceBundle {
   protected Object[][] getContents();
}

-keep public class com.google.android.gms.common.internal.safeparcel.SafeParcelable {
   public static final *** NULL;
}

-keepnames @com.google.android.gms.common.annotation.KeepName class *
-keepclassmembernames class * {
   @com.google.android.gms.common.annotation.KeepName *;
}

-keepnames class * implements android.os.Parcelable {
   public static final ** CREATOR;
}

-keep public class com.bumptech.glide.**
```

**Comment by mahdi-malv** [comment]
Latest update

Tapsell sdk for RN is no longer maintained. Instead use [Tapsell plus plugin](https://github.com/tapsellorg/TapsellPlusSDK-ReactNativePlugin)

[Docs](https://docs.tapsell.ir/plus-sdk/reactnative/initialize-android/)
