### ISSUE TITLE
Android app crash after version 4.5.0

### ISSUE THREAD

**Issue by bodaghialib4** [tapsellorg/TapsellSDK-ReactNativePlugin#5]
Hi, 
our app worked fine with version 4.1.7 but after upgrading into version 4.5.0, our app crash while starting to play video advertisement.

platform:
   `Android`

react-native version:
   ` "react-native": "^0.61.2",`

react-native-tapsell previous version:
    `"react-native-tapsell": "^4.1.7",`

react-native-tapsell version after updating:
   ` "react-native-tapsell": "^4.5.0",`

exception in `adb logcat`:

```
E unknown:ReactNative: Exception in native call
E unknown:ReactNative: java.lang.NullPointerException: Attempt to invoke virtual method 'double java.lang.Double.doubleValue()' on a null object reference
E unknown:ReactNative: 	at com.facebook.react.bridge.ReadableNativeArray.getDouble(ReadableNativeArray.java:91)
E unknown:ReactNative: 	at com.facebook.react.bridge.JavaMethodWrapper$4.extractArgument(JavaMethodWrapper.java:63)
E unknown:ReactNative: 	at com.facebook.react.bridge.JavaMethodWrapper$4.extractArgument(JavaMethodWrapper.java:59)
E unknown:ReactNative: 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:355)
E unknown:ReactNative: 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:150)
E unknown:ReactNative: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
E unknown:ReactNative: 	at android.os.Handler.handleCallback(Handler.java:739)
E unknown:ReactNative: 	at android.os.Handler.dispatchMessage(Handler.java:95)
E unknown:ReactNative: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26)
E unknown:ReactNative: 	at android.os.Looper.loop(Looper.java:148)
E unknown:ReactNative: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225)
E unknown:ReactNative: 	at java.lang.Thread.run(Thread.java:818)
```

debugging error in the emulator:

<img width="476" alt="Screen Shot 1399-07-06 at 11 16 17" src="https://user-images.githubusercontent.com/23075818/94364627-a91ab300-00d7-11eb-8cbe-f42732970921.png">

For a temporary solution I forced our app to use version 4.1.7 (by removing `^` from the version number):
   ` "react-native-tapsell": "4.1.7",`

**Comment by bodaghialib4** [comment]
<img width="602" alt="Screen Shot 1399-07-06 at 11 52 56" src="https://user-images.githubusercontent.com/23075818/94366942-2fd78c00-00e8-11eb-8bd2-d74cfb414e37.png">


I find out that it is required to pass zoneId when calling `showAd`, but it doesn't solve my problem. 


our previous code:

```js

Tapsell.showAd(
    {
        ad_id: adId,
        back_disabled: false,
        immersive_mode: true,
        rotation_mode: Tapsell.ROTATION_LOCKED_PORTRAIT,
        show_exit_dialog: true
    },
    (zoneId, adId) => {
        console.log("+++++++++++++++++++ ad opened");
    },
    (zoneId, adId) => {
        console.log("+++++++++++++++++++ ad closed");
    });

},

```


updated code:

```js

Tapsell.showAd(
    {
        ad_id: adId,
        zone_id: zoneId, //  <<<<<<<<<<<<<<  this part added
        back_disabled: false,
        immersive_mode: true,
        rotation_mode: Tapsell.ROTATION_LOCKED_PORTRAIT,
        show_exit_dialog: true
    },
    (zoneId, adId) => {
        console.log("+++++++++++++++++++ ad opened");
    },
    (zoneId, adId) => {
        console.log("+++++++++++++++++++ ad closed");
    });

},

```


I wish this package had at least a document.

**Comment by mahdi-malv** [comment]
New contributor here,

Tapsell plugin is no longer supported and instead all functionality is migrated to [Tapsell plus plugin](https://docs.tapsell.ir/plus-sdk/reactnative/main/) 

Any issues or problems found will be checked ASAP.

I'll close the issue. Please consider opening a new issue in [Tapsell-Plus RN issues](https://github.com/tapsellorg/TapsellPlusSDK-ReactNativePlugin/issues).

Thanks in advance
