### ISSUE TITLE
خطا در اجرای برنامه پس از نصب این پکیج

### ISSUE THREAD

**Issue by theInfiTualEr** [tapsellorg/TapsellSDK-ReactNativePlugin#6]
![Screenshot_1619476860](https://user-images.githubusercontent.com/47613413/116160116-ae3fef00-a706-11eb-92d6-b3fadaee0975.png)
ارور بالا رو چه در محیط ری اکت نیتیو خالص تازه راه اندازی شده، چه در محیط اکسپو خالص تازه راه اندازی شده، بعد از نصب پکیج ری اکت نیتیو تپسل و لینک کردنش میبینم.

**Comment by mahdi-malv** [comment]
<div dir='rtl'>

درود

تپسل دیگه مستقیما برای ری‌اکت‌نیتیو پشتیبانی نمیشه و برای استفاده بایستی از [تپسل پلاس برای ری‌اکت‌نیتیو](https://docs.tapsell.ir/plus-sdk/reactnative/main/) استفاده کنید.

در صورتی که توی تپسل پلاس (که اخیرا ریلیز جدید و سالم داشته) مشکل مشابه وجود داشت لطفا اطلاع بدید

</div>
